### ISSUE TITLE
Error failed - Client network socket disconnected before secure TLS connection was established

### ISSUE THREAD

**Issue by karan-c3** [Lambda-Store/Community#1]
Hii, 
I have just Deployed Lambda store on Netlify functions I get following errors very often
`failed - Client network socket disconnected before secure TLS connection was established` 

Any quick workaround would help alot coz APP is in production.

**Comment by svenanderson** [comment]
@karan-c3 has reported that issue has been solved by closing the connection inside the function. I am closing the issue, feel free to re-open if needed.
