### ISSUE TITLE
medis GUI client cannot connect

### ISSUE THREAD

**Issue by grempe** [Lambda-Store/Community#2]
Trying to connect the macOS GUI Redis client called `media` fails with the following error when attempting to connect.

```
Medis only supports Redis >= 2.8 because servers older than 2.8 don't support SCAN command, which means it not possible to access keys without blocking Redis.
```

The client can be found on the App Store here:

https://apps.apple.com/us/app/medis-gui-for-redis/id1063631769?mt=12

**Comment by svenanderson** [comment]
It is a bug. It will be fixed with next release.

**Comment by svenanderson** [comment]
fixed
